/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:a18ef388-28c6-4d03-8fea-2db52e6b13fd",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_HdQGWzwlD",
    "aws_user_pools_web_client_id": "79biet16r51b7sidef6dlveqmq",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://6kqm7p3oqzevfhz4gevwk3qmyi.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
